### ISSUE TITLE
Matlab 2022b support?

### ISSUE THREAD

**Issue by jbellister-slac** [till-s/epics-labca#5]
Hi,

I was wondering if matlab 2022b is currently supported? I tried a build from source setting MATLABDIR to a 2022b installation and when trying to run it just hangs on startup. 

I tried the workarounds I saw for 2020b, first with `USE_POSIX_THREAD_PRIORITY_SCHEDULING=NO` which didn't seem to have any effect. I also tried running with 

`LD_PRELOAD=/path/to/libCom.so matlab` 

And this did get it to start. But then it hangs on attempting to exit.

Please let me know if there's anything else I might try or if you've had success with startup and exit using 2022b before, thanks!

**Comment by till-s** [comment]
I only have 2022a (not b) and can confirm that 2020a hangs on exit. This is because some work-around was installed for 2020 but it turns out 2022 needs that, too. I just pushed a change which should take care of that.

Unfortunately the LD_PRELOAD work-around is still needed. There is not much we can do about this; it is a MATLAB problem (IIRC we discussed this with mathworks but there is apparently still no solution).

HTH
-- Till
